datasets:
  pascal_voc:
    name: &dataset_name 'pascal_voc2012'
    key: 'VOCSegmentation'
    root: &root_dir './resource/dataset'
    splits:
      train:
        dataset_id: &pascal_train !join [*dataset_name, '/train']
        kwargs:
          root: *root_dir
          image_set: 'train'
          year: '2012'
          download: True
          transforms_compose_cls: 'CustomCompose'
          transforms_configs:
            - key: 'CustomRandomResize'
              kwargs:
                min_size: 256
                max_size: 1026
            - key: 'CustomRandomHorizontalFlip'
              kwargs:
                p: 0.5
            - key: 'CustomRandomCrop'
              kwargs:
                size: 513
            - key: 'CustomToTensor'
              kwargs:
            - &normalize
              key: 'CustomNormalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &pascal_val !join [*dataset_name, '/val']
        kwargs:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: True
          transforms_compose_cls: 'CustomCompose'
          transforms_configs: &val_transform
            - key: 'CustomRandomResize'
              kwargs:
                min_size: 513
                max_size: 513
            - key: 'CustomToTensor'
              kwargs:
            - *normalize
      test:
        dataset_id: &pascal_test !join [*dataset_name, '/test']
        kwargs:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: True
          transforms_compose_cls: 'CustomCompose'
          transforms_configs: *val_transform

models:
  model:
    key: &student_model_key 'deeplabv3_resnet50'
    kwargs:
      pretrained: True
      pretrained_backbone: True
      num_classes: 21
      aux_loss: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/pascal_voc2012/ce/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: &num_epochs 30
  train_data_loader:
    dataset_id: *pascal_train
    random_sample: True
    num_workers: 16
    batch_size: 16
    collate_fn: 'coco_seg_collate_fn'
    drop_last: True
    cache_output:
  val_data_loader:
    dataset_id: *pascal_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'coco_seg_eval_collate_fn'
  model:
    adaptations:
    sequential: []
    forward_hook:
      input: []
      output: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'SGD'
    kwargs:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0001
    module_wise_kwargs:
      - module: 'backbone'
        kwargs: {}
      - module: 'classifier'
        kwargs: {}
      - module: 'aux_classifier'
        kwargs:
          lr: 0.01
  scheduler:
    key: 'poly_lr_scheduler'
    kwargs:
      num_iterations: None
      num_epochs: *num_epochs
      power: 0.9
    scheduling_step: 1
  criterion:
    key: 'WeightedSumLoss'
    func2extract_model_loss: 'extract_model_loss_dict'
    kwargs:
      sub_terms:
        ce:
          criterion:
            key: 'CrossEntropyLoss'
            kwargs:
              reduction: 'mean'
              ignore_index: 255
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: '.'
                io: 'output'
              target:
                uses_label: True
          weight:
            out: 1.0
            aux: 0.5

test:
  test_data_loader:
    dataset_id: *pascal_test
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'coco_seg_eval_collate_fn'