datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - type: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              kwargs:
            - &normalize
              type: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - type: 'Resize'
              kwargs:
                size: 256
            - type: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet34'
    kwargs:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./imagenet/at/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 100
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 256
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  teacher:
    sequential: []
    forward_hook:
      input: []
      output: ['layer3', 'layer4']
    wrapper: 'DataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    frozen_modules: []
    forward_hook:
      input: []
      output: ['layer3', 'layer4']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    type: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    kwargs:
      milestones: [30, 60, 90]
      gamma: 0.1
  criterion:
    type: 'WeightedSumLoss'
    model_term:
      criterion:
        type: 'CrossEntropyLoss'
        kwargs:
          reduction: 'mean'
      factor: 1.0
    sub_terms:
      at_loss:
        criterion:
          type: 'ATLoss'
          kwargs:
            at_pairs:
              pair1:
                teacher:
                  io: 'output'
                  path: 'layer3'
                student:
                  io: 'output'
                  path: 'layer3'
                factor: 1
              pair2:
                teacher:
                  io: 'output'
                  path: 'layer4'
                student:
                  io: 'output'
                  path: 'layer4'
                factor: 1
            mode: 'code'
        factor: 1000.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
