datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - type: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              kwargs:
            - &normalize
              type: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - type: 'Resize'
              kwargs:
                size: 256
            - type: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet34'
    kwargs:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./imagenet/crd/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 100
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 85
    num_workers: 16
    dataset_wrapper:
      name: 'ContrastiveDataset'
      kwargs:
        num_negative_samples: &num_negative_samples 16384
        mode: 'exact'
        ratio: 1.0
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  teacher:
    forward_proc: 'forward_batch_supp_dict'
    sequential: []
    auxiliary_model_wrapper:
      type: 'Linear4CRD'
      kwargs:
        input_module_path: 'model.avgpool'
        linear_kwargs:
          in_features: 512
          out_features: 128
          bias: True
        power: 2
    forward_hook:
      input: []
      output: ['model.avgpool', 'normalizer']
    wrapper:
    requires_grad: True
    frozen_modules: ['model']
  student:
    forward_proc: 'forward_batch_supp_dict'
    adaptations:
    sequential: []
    auxiliary_model_wrapper:
      type: 'Linear4CRD'
      kwargs:
        input_module_path: 'model.avgpool'
        linear_kwargs:
          in_features: 512
          out_features: &feature_dim 128
          bias: True
        power: 2
    forward_hook:
      input: ['empty']
      output: ['model.avgpool', 'normalizer']
    wrapper:
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    kwargs:
      milestones: [30, 60, 90]
      gamma: 0.1
  criterion:
    type: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        ce:
          criterion:
            type: 'CrossEntropyLoss'
            kwargs:
              reduction: 'mean'
          criterion_wrapper:
            type: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: '.'
                io: 'output'
              target:
                uses_label: True
          weight: 1.0
        crd:
          criterion:
            type: 'CRDLoss'
            kwargs:
              teacher_norm_module_path: 'normalizer'
              student_norm_module_path: 'normalizer'
              student_empty_module_path: 'empty'
              input_size: *feature_dim
              output_size: &num_samples 1281167
              num_negative_samples: *num_negative_samples
              num_samples: *num_samples
              temperature: 0.07
              momentum: 0.5
              eps: 0.0000001
          weight: 0.8

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
