datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    key: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - key: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - key: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              key: 'ToTensor'
              kwargs:
            - &normalize
              key: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - key: 'Resize'
              kwargs:
                size: 256
            - key: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    key: &teacher_model_key 'resnet34'
    kwargs:
      num_classes: 1000
      pretrained: True
    src_ckpt:
  student_model:
    key: &student_model_key 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    src_ckpt:
    dst_ckpt: !join ['./imagenet_1gpu/ft_normal/', *student_experiment, '.pt']

train:
  log_freq: 1000
  stage1:
    num_epochs: 1
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 256
      num_workers: 16
      cache_output:
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 256
      num_workers: 16
    teacher:
      sequential: []
      auxiliary_model_wrapper:
        key: &teacher4ft 'Teacher4FactorTransfer'
        kwargs:
          minimal:
            sequential: ['conv1', 'bn1', 'relu', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4']
          input_module_path: &teacher4ft_in_module 'teacher_model.layer4'
          paraphraser_kwargs: &teacher4ft_paraphraser_kwargs
            k: 0.5
            num_input_channels: 512
            kernel_size: 3
            stride: 1
            padding: 1
            uses_bn: False
          paraphraser_ckpt: &teacher4ft_paraphraser_ckpt !join ['./imagenet/ft/', *student_experiment, '_paraphraser.pt']
          uses_decoder: True
      forward_hook:
        input: []
        output: ['teacher_model.layer4', 'paraphraser']
      wrapper:
      requires_grad: True
      frozen_modules: ['teacher_model']
    student:
      adaptations:
      auxiliary_model_wrapper:
        key: 'EmptyModule'
        kwargs:
      sequential: []
      forward_hook:
        input: []
        output: []
      wrapper:
      requires_grad: False
    optimizer:
      key: 'SGD'
      kwargs:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0001
    criterion:
      key: 'WeightedSumLoss'
      sub_terms:
        reconst:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'mean'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: True
                module_path: 'paraphraser'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'teacher_model.layer4'
                io: 'output'
          weight: 1.0
  stage2:
    num_epochs: 90
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 256
      num_workers: 16
      cache_output:
    teacher:
      sequential: []
      auxiliary_model_wrapper:
        key: *teacher4ft
        kwargs:
          minimal:
          input_module_path: *teacher4ft_in_module
          paraphraser_kwargs: *teacher4ft_paraphraser_kwargs
          paraphraser_ckpt: *teacher4ft_paraphraser_ckpt
          uses_decoder: False
      forward_hook:
        input: []
        output: ['teacher_model.layer4', 'paraphraser']
      wrapper:
      requires_grad: False
    student:
      adaptations:
      sequential: []
      auxiliary_model_wrapper:
        key: 'Student4FactorTransfer'
        kwargs:
          input_module_path: 'student_model.layer4'
          translator_kwargs:
            num_input_channels: 512
            num_output_channels: 256
            kernel_size: 3
            stride: 1
            padding: 1
            uses_bn: False
      forward_hook:
        input: []
        output: ['student_model.layer4', 'translator']
      wrapper:
      requires_grad: True
      frozen_modules: []
    optimizer:
      key: 'SGD'
      kwargs:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0001
    scheduler:
      key: 'MultiStepLR'
      kwargs:
        milestones: [30, 60, 90]
        gamma: 0.1
    criterion:
      key: 'WeightedSumLoss'
      kwargs:
        sub_terms:
          ce:
            criterion:
              key: 'CrossEntropyLoss'
              kwargs:
                reduction: 'mean'
            criterion_wrapper:
              key: 'SimpleLossWrapper'
              kwargs:
                input:
                  is_from_teacher: False
                  module_path: '.'
                  io: 'output'
                target:
                  uses_label: True
            weight: 1.0
          factor_transfer:
            criterion:
              key: 'FTLoss'
              kwargs:
                p: 1
                reduction: 'mean'
                paraphraser_path: 'paraphraser'
                translator_path: 'translator'
            weight: 1000.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
