datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    key: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - key: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - key: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              key: 'ToTensor'
              kwargs:
            - &normalize
              key: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - key: 'Resize'
              kwargs:
                size: 256
            - key: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    key: &teacher_model_key 'resnet34'
    kwargs:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_key]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    key: &student_model_key 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    ckpt: !join ['./imagenet/sskd/', *student_experiment, '.pt']

train:
  log_freq: 1000
  stage1:
    num_epochs: 30
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 85
      num_workers: 16
      dataset_wrapper:
        key: 'SSKDDatasetWrapper'
        kwargs: {}
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 128
      num_workers: 16
    teacher:
      forward_proc: 'forward_batch4sskd'
      sequential: []
      auxiliary_model_wrapper:
        key: 'SSWrapper4SSKD'
        kwargs:
          input_module: &teacher4sskd_in_module
            path: 'model.avgpool'
            io: 'output'
          feat_dim: &teacher4sskd_feat_dim 512
          freezes_ss_module: False
          ss_module_ckpt: &teacher4sskd_ckpt !join ['./imagenet/sskd/', *student_experiment, '_teacher_ss_module.pt']
      forward_hook:
        input: []
        output: ['model.avgpool', 'ss_module']
      wrapper:
      requires_grad: True
      frozen_modules: ['model']
    student:
      adaptations:
      auxiliary_model_wrapper:
        key: 'EmptyModule'
        kwargs:
      sequential: []
      forward_hook:
        input: []
        output: []
      wrapper:
      requires_grad: False
    optimizer:
      key: 'SGD'
      kwargs:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
      key: 'MultiStepLR'
      kwargs:
        milestones: [10, 20]
        gamma: 0.1
    criterion:
      key: 'WeightedSumLoss'
      sub_terms:
        aux_task:
          criterion:
            key: 'AuxSSKDLoss'
            kwargs:
              module_path: 'ss_module'
              module_io: 'output'
              reduction: 'mean'
          weight: 1.0
  stage2:
    num_epochs: 100
    teacher:
      forward_proc: 'forward_batch4sskd'
      sequential: []
      auxiliary_model_wrapper:
        key: 'SSWrapper4SSKD'
        kwargs:
          input_module: *teacher4sskd_in_module
          feat_dim: *teacher4sskd_feat_dim
          freezes_ss_module: True
          ss_module_ckpt: *teacher4sskd_ckpt
      forward_hook:
        input: []
        output: ['model.avgpool', 'model.fc', 'ss_module']
      wrapper:
      requires_grad: False
    student:
      forward_proc: 'forward_batch4sskd'
      adaptations:
      sequential: []
      auxiliary_model_wrapper:
        key: 'SSWrapper4SSKD'
        kwargs:
          input_module:
            path: 'model.avgpool'
            io: 'output'
          feat_dim: 512
          freezes_ss_module: False
          ss_module_ckpt: !join ['./imagenet/sskd/', *student_experiment, '_student_ss_module.pt']
      forward_hook:
        input: []
        output: ['model.avgpool', 'model.fc', 'ss_module']
      wrapper:
      requires_grad: True
      frozen_modules: []
    optimizer:
      key: 'SGD'
      kwargs:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
      key: 'MultiStepLR'
      kwargs:
        milestones: [30, 60, 90]
        gamma: 0.1
    criterion:
      key: 'WeightedSumLoss'
      kwargs:
        sub_terms:
          sskd:
            criterion:
              key: 'SSKDLoss'
              kwargs:
                student_linear_module_path: 'model.fc'
                teacher_linear_module_path: 'model.fc'
                student_ss_module_path: 'ss_module'
                teacher_ss_module_path: 'ss_module'
                kl_temp: 4.0
                ss_temp: 0.5
                tf_temp: 4.0
                ss_ratio: 0.75
                tf_ratio: 1.0
                loss_weights: [1.0, 0.9, 10.0, 2.7]
                reduction: 'batchmean'
            weight: 1.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
