datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    key: 'ImageFolder'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - key: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - key: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              key: 'ToTensor'
              kwargs:
            - &normalize
              key: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - key: 'Resize'
              kwargs:
                size: 256
            - key: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    key: &teacher_model_key 'resnet50'
    kwargs:
      num_classes: 1000
      pretrained: True
    src_ckpt:
  student_model:
    key: &student_model_key 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/ilsvrc2012/single_stage/crd/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 32
    num_workers: 16
    dataset_wrapper:
      key: 'ContrastiveDataset'
      kwargs:
        num_negative_samples: &num_negative_samples 16384
        mode: 'exact'
        ratio: 1.0
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 16
  teacher:
    forward_proc: 'forward_batch_supp_dict'
    sequential: []
    auxiliary_model_wrapper:
      key: 'Linear4CRD'
      kwargs:
        input_module_path: 'model.avgpool'
        linear_kwargs:
          in_features: 2048
          out_features: 128
          bias: True
        power: 2
    forward_hook:
      input: []
      output: ['model.avgpool', 'normalizer']
    wrapper:
    requires_grad: True
    frozen_modules: ['model']
  student:
    forward_proc: 'forward_batch_supp_dict'
    adaptations:
    sequential: []
    auxiliary_model_wrapper:
      key: 'Linear4CRD'
      kwargs:
        input_module_path: 'model.avgpool'
        linear_kwargs:
          in_features: 512
          out_features: &feature_dim 128
          bias: True
        power: 2
    forward_hook:
      input: ['empty']
      output: ['model.avgpool', 'normalizer']
    wrapper:
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'SGD'
    kwargs:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [5, 15]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            key: 'KDLoss'
            kwargs:
              student_module_path: '.'
              student_module_io: 'output'
              teacher_module_path: '.'
              teacher_module_io: 'output'
              temperature: 4.0
              alpha: 0.5
              reduction: 'batchmean'
          weight: 2.0
        crd:
          criterion:
            key: 'CRDLoss'
            kwargs:
              teacher_norm_module_path: 'normalizer'
              student_norm_module_path: 'normalizer'
              student_empty_module_path: 'empty'
              input_size: *feature_dim
              output_size: &num_samples 1281167
              num_negative_samples: *num_negative_samples
              num_samples: *num_samples
              temperature: 0.07
              momentum: 0.5
              eps: 0.0000001
          weight: 0.8

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
