datasets:
  cifar10:
    name: &dataset_name 'cifar10'
    type: 'CIFAR10'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      dummy:
        dataset_id: 'dummy'
        kwargs:
          root: *root_dir
          train: True
          download: True
        random_split:
          lengths: [0.9, 0.1]
          generator_seed: 42
          sub_splits:
            - dataset_id: &cifar10_train !join [*dataset_name, '/train']
              transform_configs:
                - type: 'RandomCrop'
                  kwargs:
                    size: 32
                    padding: 4
                - type: 'RandomHorizontalFlip'
                  kwargs:
                    p: 0.5
                - type: 'ToTensor'
                  kwargs:
                - &normalize
                  type: 'Normalize'
                  kwargs:
                    mean: [0.49139968, 0.48215841, 0.44653091]
                    std: [0.24703223, 0.24348513, 0.26158784]
            - dataset_id: &cifar10_val !join [*dataset_name, '/val']
              transform_configs: &val_transform
                - type: 'ToTensor'
                  kwargs:
                - *normalize
      test:
        dataset_id: &cifar10_test !join [*dataset_name, '/test']
        kwargs:
          root: *root_dir
          train: False
          download: True
          transform_configs: *val_transform

models:
  model:
    name: &student_model_name 'densenet_bc_k12_depth100'
    kwargs:
      num_classes: 10
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name]
    ckpt: !join ['./resource/ckpt/', *dataset_name, '/ce/', *student_experiment, '-hyperparameter_tuning.pt']

train:
  log_freq: 100
  num_epochs: 300
  train_data_loader:
    dataset_id: *cifar10_train
    random_sample: True
    batch_size: 64
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *cifar10_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  model:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    kwargs:
      milestones: [150, 225]
      gamma: 0.1
  criterion:
    type: 'WeightedSumLoss'
    model_term:
      criterion:
        type: 'CrossEntropyLoss'
        kwargs:
          reduction: 'mean'
      factor: 1.0
    sub_terms:

test:
  test_data_loader:
    dataset_id: *cifar10_test
    random_sample: False
    batch_size: 1
    num_workers: 16
