datasets:
  cifar10:
    name: &dataset_name 'cifar10'
    key: 'CIFAR10'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      dummy:
        dataset_id: 'dummy'
        kwargs:
          root: *root_dir
          train: True
          download: True
        random_split:
          lengths: [0.9, 0.1]
          generator_seed: 42
          sub_splits:
            - dataset_id: &cifar10_train !join [*dataset_name, '/train']
              transform_configs:
                - key: 'RandomCrop'
                  kwargs:
                    size: 32
                    padding: 4
                - key: 'RandomHorizontalFlip'
                  kwargs:
                    p: 0.5
                - key: 'ToTensor'
                  kwargs:
                - &normalize
                  key: 'Normalize'
                  kwargs:
                    mean: [0.49139968, 0.48215841, 0.44653091]
                    std: [0.24703223, 0.24348513, 0.26158784]
            - dataset_id: &cifar10_val !join [*dataset_name, '/val']
              transform_configs: &val_transform
                - key: 'ToTensor'
                  kwargs:
                - *normalize
      test:
        dataset_id: &cifar10_test !join [*dataset_name, '/test']
        kwargs:
          root: *root_dir
          train: False
          download: True
          transform_configs: *val_transform

models:
  model:
    key: &student_model_key 'resnet44'
    kwargs:
      num_classes: 10
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key]
    ckpt: !join ['./resource/ckpt/', *dataset_name, '/ce/', *student_experiment, '-hyperparameter_tuning.pt']

train:
  log_freq: 100
  num_epochs: 182
  train_data_loader:
    dataset_id: *cifar10_train
    random_sample: True
    batch_size: 128
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *cifar10_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  model:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [91, 136]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        ce:
          criterion:
            key: 'CrossEntropyLoss'
            kwargs:
              reduction: 'mean'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: '.'
                io: 'output'
              target:
                uses_label: True
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *cifar10_test
    random_sample: False
    batch_size: 1
    num_workers: 16
