datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - type: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              kwargs:
            - &normalize
              type: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - type: 'Resize'
              kwargs:
                size: 256
            - type: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet50'
    kwargs:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    kwargs:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/single_stage/vid/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 32
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 16
  teacher:
    sequential: []
    forward_hook:
      input: []
      output: ['layer1', 'layer2', 'layer3', 'layer4']
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    auxiliary_model_wrapper:
      type: 'VariationalDistributor4VID'
      kwargs:
        regressors:
          regressor1:
            io: 'output'
            path: 'student_model.layer1'
            regressor_kwargs:
              in_channels: 64
              middle_channels: &och1 256
              out_channels: *och1
              eps: 0.00001
              init_pred_var: 5.0
          regressor2:
            io: 'output'
            path: 'student_model.layer2'
            regressor_kwargs:
              in_channels: 128
              middle_channels: &och2 512
              out_channels: *och2
              eps: 0.00001
              init_pred_var: 5.0
          regressor3:
            io: 'output'
            path: 'student_model.layer3'
            regressor_kwargs:
              in_channels: 256
              middle_channels: &och3 1024
              out_channels: *och3
              eps: 0.00001
              init_pred_var: 5.0
          regressor4:
            io: 'output'
            path: 'student_model.layer4'
            regressor_kwargs:
              in_channels: 512
              middle_channels: &och4 2048
              out_channels: *och4
              eps: 0.00001
              init_pred_var: 5.0
    frozen_modules: []
    forward_hook:
      input: []
      output: ['student_model.layer1', 'student_model.layer2', 'student_model.layer3', 'student_model.layer4', 'regressor_dict.regressor1', 'regressor_dict.regressor2', 'regressor_dict.regressor3', 'regressor_dict.regressor4']
    wrapper:
    requires_grad: True
  optimizer:
    type: 'SGD'
    kwargs:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    kwargs:
      milestones: [5, 10]
      gamma: 0.1
  criterion:
    type: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            type: 'KDLoss'
            kwargs:
              student_module_path: '.'
              student_module_io: 'output'
              teacher_module_path: '.'
              teacher_module_io: 'output'
              temperature: 1.0
              alpha: 1.0
              reduction: 'batchmean'
          factor: 1.0
        vid:
          criterion:
            type: 'VIDLoss'
            kwargs:
              feature_pairs:
                pair1:
                  teacher:
                    io: 'output'
                    path: 'layer1'
                  student:
                    io: 'output'
                    path: 'regressor_dict.regressor1'
                  factor: 1
                pair2:
                  teacher:
                    io: 'output'
                    path: 'layer2'
                  student:
                    io: 'output'
                    path: 'regressor_dict.regressor2'
                  factor: 1
                pair3:
                  teacher:
                    io: 'output'
                    path: 'layer3'
                  student:
                    io: 'output'
                    path: 'regressor_dict.regressor3'
                  factor: 1
                pair4:
                  teacher:
                    io: 'output'
                    path: 'layer4'
                  student:
                    io: 'output'
                    path: 'regressor_dict.regressor4'
                  factor: 1
              margin: 1.0
          factor: 1.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
